# generated by datamodel-codegen:
#   filename:  tmpj_8zzv0f.json
#   timestamp: 2025-06-21T16:54:11+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Mapping, Sequence

from pydantic import BaseModel, ConfigDict, Field


class Engine(Enum):
    """
    The physics engine responsible for this object.
    """

    quantum = 'quantum'
    classical = 'classical'
    hybrid = 'hybrid'


class PhysicsProperties(BaseModel):
    """
    Defines the common physics-related properties for components and laws.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    collapse_sensitive: Annotated[
        bool | None,
        Field(
            description='Indicates if the object is affected by or triggers quantum collapse.'
        ),
    ]
    engine: Annotated[
        Engine, Field(description='The physics engine responsible for this object.')
    ]
    is_quantum: Annotated[
        bool, Field(description='Indicates if the object has quantum properties.')
    ]


class Fields(BaseModel):
    """
    A direct reference to a shared definition in SharedDefinitions.schema.json.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    field_ref: Annotated[str, Field(alias='$ref')]


class Type(str, Enum):
    """
    A primitive type, represented as a string from a controlled vocabulary.
    """

    string = 'string'
    boolean = 'boolean'
    integer = 'integer'
    number = 'number'
    f32 = 'f32'
    f64 = 'f64'
    i32 = 'i32'
    i64 = 'i64'
    u32 = 'u32'
    u64 = 'u64'
    uuid = 'uuid'
    date_time = 'date-time'
    duration = 'duration'
    object = 'object'
    array = 'array'


class Type1(BaseModel):
    """
    A complex, contrived meta-type, represented by a reference to its canonical schema file.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    field_ref: Annotated[str, Field(alias='$ref')]


class Constraints(BaseModel):
    """
    A canonical definition for field validation constraints.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    minimum: float | None
    maximum: float | None
    minLength: int | None
    maxLength: int | None
    pattern: str | None
    enum: Sequence[str] | None


class Fields1(BaseModel):
    """
    Defines the structure for a single, inline field definition within a component.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    description: Annotated[
        str,
        Field(
            description='A canonical, reusable definition for a human-readable description field.',
            title='Description Field',
        ),
    ]
    type: Annotated[
        Type | Type1,
        Field(
            description='The canonical list of all valid primitive and complex data types used within the Familiar engine. A type can be a primitive string or a reference to a complex type schema.',
            title='Base Type System',
        ),
    ]
    default_value: Annotated[
        str | float | int | bool | Mapping[str, Any] | Sequence[Any] | None,
        Field(
            description="Represents any valid JSON value. Used for fields with dynamic or unknown types, like 'default' values.",
            title='Any Value',
        ),
    ] = None
    constraints: Annotated[
        Constraints | None,
        Field(
            description='A canonical definition for field validation constraints.',
            title='Constraint Definition',
        ),
    ]
    ui_label: str | None


class BondTension(BaseModel):
    """
    Models the classical physics of a relationship Bond, including its strength, tension, and resonance properties. This is managed by the Particular engine.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    physics_properties: Annotated[
        PhysicsProperties,
        Field(
            description='Defines the common physics-related properties for components and laws.',
            title='Base Physics Properties',
        ),
    ]
    fields: Annotated[
        Mapping[str, Fields | Fields1],
        Field(
            description='A map of field names to their definitions. Each field can be defined inline or by referencing a shared definition.',
            title='BaseFields',
        ),
    ]
