# generated by datamodel-codegen:
#   filename:  tmpo4lox905.json
#   timestamp: 2025-06-21T03:58:30+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Engine(Enum):
    """
    The physics engine responsible for this object.
    """

    quantum = 'quantum'
    classical = 'classical'
    hybrid = 'hybrid'


class PhysicsProperties(BaseModel):
    """
    Defines the common physics-related properties for components and laws.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    collapse_sensitive: Annotated[
        bool | None,
        Field(
            description='Indicates if the object is affected by or triggers quantum collapse.'
        ),
    ]
    engine: Annotated[
        Engine, Field(description='The physics engine responsible for this object.')
    ]
    is_quantum: Annotated[
        bool, Field(description='Indicates if the object has quantum properties.')
    ]


class ConsolidationLevel(str, Enum):
    """
    A canonical enum for the temporal consolidation level of a Motif or Filament.
    """

    Daily = 'Daily'
    Weekly = 'Weekly'
    Monthly = 'Monthly'
    Yearly = 'Yearly'
    Archived = 'Archived'


class Fields(BaseModel):
    """
    A map of field names to their definitions. Each field can be defined inline or by referencing a shared definition.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    consolidation_level: Annotated[
        ConsolidationLevel,
        Field(
            description='A canonical enum for the temporal consolidation level of a Motif or Filament.',
            title='Consolidation Level',
        ),
    ]
    last_consolidated_at: Annotated[
        str | None,
        Field(
            description='A canonical definition for an optional ISO 8601 timestamp with timezone.',
            title='Nullable Timestamp',
        ),
    ] = None
    next_consolidation_due: Annotated[
        str | None,
        Field(
            description='A canonical definition for an optional ISO 8601 timestamp with timezone.',
            title='Nullable Timestamp',
        ),
    ] = None
    source_entity_count: Annotated[int, Field(ge=1)]


class ConsolidationState(BaseModel):
    """
    Tracks the temporal consolidation state of a Motif or Filament.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    physics_properties: Annotated[
        PhysicsProperties,
        Field(
            description='Defines the common physics-related properties for components and laws.',
            title='Base Physics Properties',
        ),
    ]
    fields: Annotated[
        Fields,
        Field(
            description='A map of field names to their definitions. Each field can be defined inline or by referencing a shared definition.',
            title='ConsolidationStateFields',
        ),
    ]
