# generated by datamodel-codegen:
#   filename:  tmp3ohprdpr.json
#   timestamp: 2025-06-21T16:54:52+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import ConfigDict, Field, RootModel


class ThreadEnergyDecay(RootModel[Any]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Any,
        Field(
            description='Applies a natural, exponential decay to the energy level of all Thread entities over time, representing the natural settling of cognitive activation.',
            title='Thread Energy Decay Law',
        ),
    ]
