# generated by datamodel-codegen:
#   filename:  tmpmxi42d2v.json
#   timestamp: 2025-06-21T04:00:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Sequence

from pydantic import BaseModel, ConfigDict, Field


class RelationshipType(str, Enum):
    """
    A canonical enum of all possible relationship types between Threads.
    """

    Family = 'Family'
    Friend = 'Friend'
    Romantic = 'Romantic'
    Professional = 'Professional'
    Acquaintance = 'Acquaintance'
    Adversarial = 'Adversarial'


class History(BaseModel):
    """
    Represents a significant event that impacted a bond's strength or state.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    moment_id: str
    impact: Annotated[
        float,
        Field(
            description='How much this event affected the bond, from -1.0 (negative) to 1.0 (positive).',
            ge=-1.0,
            le=1.0,
        ),
    ]
    timestamp: Annotated[
        str,
        Field(
            description='A canonical definition for an ISO 8601 timestamp with timezone.',
            title='Timestamp',
        ),
    ]


class Fields(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    relationship_type: Annotated[
        RelationshipType,
        Field(
            description='A canonical enum of all possible relationship types between Threads.',
            title='Relationship Type',
        ),
    ]
    description: Annotated[
        str | None,
        Field(
            description='A canonical, reusable definition for a human-readable description field.',
            title='Description Field',
        ),
    ] = ''
    history: Sequence[History] | None


class Content(BaseModel):
    """
    Defines the descriptive content and history of a relationship Bond.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    fields: Annotated[Fields | None, Field(title='BondContentFields')]


class Components(BaseModel):
    """
    Component references temporarily disabled for pipeline testing
    """

    model_config = ConfigDict(
        frozen=True,
    )
    field_comment: Annotated[
        str | None,
        Field(
            alias='_comment',
            description='TODO: Re-enable component references when component schemas are available',
        ),
    ]
    content: Annotated[
        Content,
        Field(
            description='Defines the descriptive content and history of a relationship Bond.',
            title='Bond Content Component',
        ),
    ]
    permissions: Annotated[
        Any,
        Field(
            description='Defines the access control and privacy rules for a Bond and its associated Moments.',
            title='Bond Permissions Component',
        ),
    ]
    physics_config: Annotated[
        Any,
        Field(
            description='Configuration that defines the physics model for a Bond (Dynamic or Static).',
            title='Bond Physics Config Component',
        ),
    ]


class EntityType(str, Enum):
    """
    A canonical enum of all 7 cognitive entity types.
    """

    Focus = 'Focus'
    Filament = 'Filament'
    Motif = 'Motif'
    Intent = 'Intent'
    Moment = 'Moment'
    Bond = 'Bond'
    Thread = 'Thread'


class DecayRate(BaseModel):
    """
    The base rate of energy or coherence decay for an entity, before multipliers are applied.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    value: float


class ConsolidationRate(BaseModel):
    """
    The base rate of memory consolidation for an entity, before multipliers are applied. Represents how quickly an unstable memory becomes stable.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    value: Annotated[float, Field(ge=0.0, le=1.0)]


class Fields1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    energy: Annotated[
        float, Field(description='The current energy level of an entity.')
    ]
    momentum: Annotated[
        Sequence[float],
        Field(
            description='A reusable data type for a vector of six f64 numbers, used for momentum and forces in the 6 spatial dimensions of the manifold.',
            max_length=6,
            min_length=6,
            title='6D Physics Vector',
        ),
    ]
    cognitive_perspective: Annotated[
        Any,
        Field(
            description="The intrinsic 'spin' or 'flavor' of the entity, which generates cognitive dissonance (torsion).",
            title='Cognitive Perspective Field',
        ),
    ]
    decay_rate: Annotated[
        DecayRate,
        Field(
            description='The base rate of energy or coherence decay for an entity, before multipliers are applied.'
        ),
    ]
    consolidation_rate: Annotated[
        ConsolidationRate,
        Field(
            description='The base rate of memory consolidation for an entity, before multipliers are applied. Represents how quickly an unstable memory becomes stable.',
            title='Consolidation Rate Field',
        ),
    ]
    quantum_coherence: Annotated[
        float | None,
        Field(
            description='The quantum coherence level of the entity, representing its degree of superposition. Null for classical entities.',
            ge=0.0,
            le=1.0,
        ),
    ] = None
    entanglement_strength: Annotated[
        float | None,
        Field(
            description='The overall entanglement strength of this entity with others. Null for classical entities.',
            ge=0.0,
            le=1.0,
        ),
    ] = None


class Universal(BaseModel):
    """
    The transient, mutable physics state of an entity.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    fields: Annotated[Fields1 | None, Field(title='UniversalPhysicsStateFields')]


class PhysicsState(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    universal: Annotated[
        Universal,
        Field(
            description='The transient, mutable physics state of an entity.',
            title='Universal Physics State Component',
        ),
    ]
    tension: Annotated[
        Any,
        Field(
            description='Models the classical physics of a relationship Bond, including its strength, tension, and resonance properties. This is managed by the Particular engine.',
            title='Bond Tension Component',
        ),
    ]


class Bond(BaseModel):
    """
    A classical entity representing a persistent relationship between two Thread entities.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    components: Annotated[
        Components,
        Field(
            description='Component references temporarily disabled for pipeline testing',
            title='BondComponents',
        ),
    ]
    entity_type: Annotated[
        EntityType,
        Field(
            description='A canonical enum of all 7 cognitive entity types.',
            title='Entity Type',
        ),
    ]
    thread_a_id: Annotated[
        str,
        Field(
            description='A reusable definition for a unique entity identifier.',
            title='Entity ID Field',
        ),
    ]
    thread_b_id: Annotated[
        str,
        Field(
            description='A reusable definition for a unique entity identifier.',
            title='Entity ID Field',
        ),
    ]
    physics_state: Annotated[PhysicsState, Field(title='BondPhysicsState')]
