# generated by datamodel-codegen:
#   filename:  tmp55nvqcod.json
#   timestamp: 2025-06-21T04:00:55+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import ConfigDict, Field, RootModel


class EmotionalValence(RootModel[Any]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Any,
        Field(
            description='A 2-level classification for emotional content based on a simplified valence-arousal model.',
            title='Emotional Valence Taxonomy',
        ),
    ]
