# generated by datamodel-codegen:
#   filename:  tmpd0uti61w.json
#   timestamp: 2025-06-21T16:54:50+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import ConfigDict, Field, RootModel


class PhysicsProfile(RootModel[Any]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Any,
        Field(
            description='The 4-level classification system for assigning a physics profile to a cognitive entity based on its semantic content.',
            title='Physics Profile Taxonomy',
        ),
    ]
