# generated by datamodel-codegen:
#   filename:  tmp6vwm0pw0.json
#   timestamp: 2025-06-21T03:58:51+00:00

from __future__ import annotations

from enum import Enum


class AbstractionLevel(str, Enum):
    """
    A canonical enum for the level of abstraction of a cognitive entity.
    """

    Low = 'Low'
    Medium = 'Medium'
    High = 'High'
