# generated by datamodel-codegen:
#   filename:  tmpexwom8bb.json
#   timestamp: 2025-06-21T16:54:19+00:00

from __future__ import annotations

from enum import Enum


class AccessType(str, Enum):
    """
    Describes the method or reason for an entity access event.
    """

    DirectQuery = 'DirectQuery'
    SearchResult = 'SearchResult'
    ConsolidationProcess = 'ConsolidationProcess'
    AgentAnalysis = 'AgentAnalysis'
    UserInteraction = 'UserInteraction'
