# generated by datamodel-codegen:
#   filename:  tmpd9k2qa5b.json
#   timestamp: 2025-06-21T16:54:19+00:00

from __future__ import annotations

from typing import Annotated, Sequence

from pydantic import ConfigDict, Field, RootModel


class Aliases(RootModel[Sequence[str]]):
    """
    A list of alternative names for this Thread (e.g., nicknames).
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Sequence[str],
        Field(
            description='A list of alternative names for this Thread (e.g., nicknames).',
            title='Aliases',
        ),
    ]
