# generated by datamodel-codegen:
#   filename:  tmpfrm253ut.json
#   timestamp: 2025-06-21T03:58:56+00:00

from __future__ import annotations

from typing import Annotated, Any, Mapping, Sequence

from pydantic import ConfigDict, Field, RootModel


class AnyValue(
    RootModel[str | float | int | bool | Mapping[str, Any] | Sequence[Any] | None]
):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str | float | int | bool | Mapping[str, Any] | Sequence[Any] | None,
        Field(
            description="Represents any valid JSON value. Used for fields with dynamic or unknown types, like 'default' values.",
            title='Any Value',
        ),
    ]
