# generated by datamodel-codegen:
#   filename:  tmp109mje4p.json
#   timestamp: 2025-06-21T03:59:05+00:00

from __future__ import annotations

from enum import Enum


class BondStateReason(str, Enum):
    """
    A canonical enum of the machine-readable reasons for a Bond state change.
    """

    UserInitiated = 'UserInitiated'
    SystemDetectedStrain = 'SystemDetectedStrain'
    PartnerAccountErased = 'PartnerAccountErased'
    RelationshipEnded = 'RelationshipEnded'
