# generated by datamodel-codegen:
#   filename:  tmpihbju9ao.json
#   timestamp: 2025-06-21T16:54:21+00:00

from __future__ import annotations

from enum import Enum


class BondPermissions(str, Enum):
    """
    A canonical enum of permissions related to a Bond.
    """

    Read = 'Read'
    Write = 'Write'
    Delete = 'Delete'
    Share = 'Share'
