# generated by datamodel-codegen:
#   filename:  tmpuzoaa3hl.json
#   timestamp: 2025-06-21T03:59:03+00:00

from __future__ import annotations

from enum import Enum


class BondState(str, Enum):
    """
    A canonical enum of all possible lifecycle states for a Bond entity.
    """

    Active = 'Active'
    Strained = 'Strained'
    Dissolved = 'Dissolved'
    Rekindled = 'Rekindled'
