# generated by datamodel-codegen:
#   filename:  tmp3a0ss6c0.json
#   timestamp: 2025-06-21T16:54:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class BondEvent(BaseModel):
    """
    Represents a significant event that impacted a bond's strength or state.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    moment_id: str
    impact: Annotated[
        float,
        Field(
            description='How much this event affected the bond, from -1.0 (negative) to 1.0 (positive).',
            ge=-1.0,
            le=1.0,
        ),
    ]
    timestamp: Annotated[
        str,
        Field(
            description='A canonical definition for an ISO 8601 timestamp with timezone.',
            title='Timestamp',
        ),
    ]
