# generated by datamodel-codegen:
#   filename:  tmplzf7fsns.json
#   timestamp: 2025-06-21T16:54:22+00:00

from __future__ import annotations

from typing import Annotated, Sequence

from pydantic import ConfigDict, Field, RootModel


class CognitivePerspective(RootModel[Sequence[float]]):
    """
    A 3D vector representing the 'spin' or perspective on a cognitive entity, orthogonal to its manifold position.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Sequence[float],
        Field(
            description="A 3D vector representing the 'spin' or perspective on a cognitive entity, orthogonal to its manifold position.",
            max_length=3,
            min_length=3,
            title='Cognitive Perspective Vector',
        ),
    ]
