# generated by datamodel-codegen:
#   filename:  tmptwoqr6xk.json
#   timestamp: 2025-06-21T16:54:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Type(str, Enum):
    string = 'string'
    integer = 'integer'
    boolean = 'boolean'
    timestamp = 'timestamp'
    uuid = 'uuid'


class ColumnDefinition(BaseModel):
    """
    Schema for defining a database table column.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    name: Annotated[
        str,
        Field(
            description='The primary, human-readable name of an entity.',
            title='Name Field',
        ),
    ]
    type: Type
    nullable: bool | None = False
    primary_key: bool | None = False
    unique: bool | None = False
