# generated by datamodel-codegen:
#   filename:  tmpc9v6wram.json
#   timestamp: 2025-06-21T16:54:23+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class CompletedAt(RootModel[str | None]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str | None,
        Field(
            description='A canonical definition for an optional ISO 8601 timestamp with timezone.',
            title='Nullable Timestamp',
        ),
    ]
