# generated by datamodel-codegen:
#   filename:  tmp1uo0l782.json
#   timestamp: 2025-06-21T16:54:23+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ComplexNumber(BaseModel):
    """
    Represents a complex number with real and imaginary parts.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    real: float
    imaginary: float
