# generated by datamodel-codegen:
#   filename:  tmpxqf4yb5o.json
#   timestamp: 2025-06-21T03:59:15+00:00

from __future__ import annotations

from typing import Sequence

from pydantic import BaseModel, ConfigDict


class ConstraintDefinition(BaseModel):
    """
    A canonical definition for field validation constraints.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    minimum: float | None
    maximum: float | None
    minLength: int | None
    maxLength: int | None
    pattern: str | None
    enum: Sequence[str] | None
