# generated by datamodel-codegen:
#   filename:  tmpej31hgq2.json
#   timestamp: 2025-06-21T03:59:13+00:00

from __future__ import annotations

from enum import Enum


class ConsolidationLevel(str, Enum):
    """
    A canonical enum for the temporal consolidation level of a Motif or Filament.
    """

    Daily = 'Daily'
    Weekly = 'Weekly'
    Monthly = 'Monthly'
    Yearly = 'Yearly'
    Archived = 'Archived'
