# generated by datamodel-codegen:
#   filename:  tmpijdtucj4.json
#   timestamp: 2025-06-21T03:59:18+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class DecayRate(BaseModel):
    """
    The base rate of energy or coherence decay for an entity, before multipliers are applied.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    value: float
