# generated by datamodel-codegen:
#   filename:  tmpvgct13qw.json
#   timestamp: 2025-06-21T16:54:26+00:00

from __future__ import annotations

from enum import Enum


class DissonanceType(str, Enum):
    """
    A canonical enum for the types of cognitive dissonance the system can detect.
    """

    TemporalOverlap = 'TemporalOverlap'
    LogicalContradiction = 'LogicalContradiction'
    LowConfidencePattern = 'LowConfidencePattern'
    UnresolvedEntity = 'UnresolvedEntity'
