# generated by datamodel-codegen:
#   filename:  tmpgh1_uq_c.json
#   timestamp: 2025-06-21T16:54:26+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class EffectiveAt(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str,
        Field(
            description='A canonical definition for an ISO 8601 timestamp with timezone.',
            title='Timestamp',
        ),
    ]
