# generated by datamodel-codegen:
#   filename:  tmphh_2a0g4.json
#   timestamp: 2025-06-21T16:54:27+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Energy(BaseModel):
    """
    The current energy level of an entity.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    value: float
