# generated by datamodel-codegen:
#   filename:  tmp336u027y.json
#   timestamp: 2025-06-21T03:59:25+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Energy(BaseModel):
    """
    The current energy level of an entity.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    value: float
