# generated by datamodel-codegen:
#   filename:  tmpv5oicl34.json
#   timestamp: 2025-06-21T03:59:27+00:00

from __future__ import annotations

from typing import Annotated, Mapping

from pydantic import ConfigDict, Field, RootModel


class EntanglementMap(RootModel[Mapping[str, float] | None]):
    """
    Schema for EntanglementMap
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[Mapping[str, float] | None, Field(ge=0.0, le=1.0)]
