# generated by datamodel-codegen:
#   filename:  tmp1zty0amy.json
#   timestamp: 2025-06-21T03:59:28+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class EntanglementStrength(RootModel[float | None]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        float | None,
        Field(
            description='The overall entanglement strength of this entity with others. Null for classical entities.',
            ge=0.0,
            le=1.0,
            title='EntanglementStrength',
        ),
    ]
