# generated by datamodel-codegen:
#   filename:  tmp0rxt4_8f.json
#   timestamp: 2025-06-21T16:54:29+00:00

from __future__ import annotations

from typing import Annotated, Sequence

from pydantic import ConfigDict, Field, RootModel


class EntityIdList(RootModel[Sequence[str]]):
    """
    A canonical definition for a list of unique entity identifiers (UUIDs).
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Sequence[str],
        Field(
            description='A canonical definition for a list of unique entity identifiers (UUIDs).',
            title='Entity ID List',
        ),
    ]
