# generated by datamodel-codegen:
#   filename:  tmpth1f61o1.json
#   timestamp: 2025-06-21T16:54:28+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class EntityId(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str,
        Field(
            description='A reusable definition for a unique entity identifier.',
            title='Entity ID Field',
        ),
    ]
