# generated by datamodel-codegen:
#   filename:  tmp3g5mwi7b.json
#   timestamp: 2025-06-21T03:59:34+00:00

from __future__ import annotations

from enum import Enum


class EntityType(str, Enum):
    """
    A canonical enum of all 7 cognitive entity types.
    """

    Focus = 'Focus'
    Filament = 'Filament'
    Motif = 'Motif'
    Intent = 'Intent'
    Moment = 'Moment'
    Bond = 'Bond'
    Thread = 'Thread'
