# generated by datamodel-codegen:
#   filename:  tmp42e_qk5k.json
#   timestamp: 2025-06-21T03:59:36+00:00

from __future__ import annotations

from enum import Enum


class FilamentType(str, Enum):
    """
    A canonical enum of the types of high-level narratives a Filament can represent.
    """

    PersonalityTrait = 'PersonalityTrait'
    Worldview = 'Worldview'
    Relationship_Pattern = 'Relationship_Pattern'
    Life_Theme = 'Life_Theme'
