# generated by datamodel-codegen:
#   filename:  tmp6gw8rklp.json
#   timestamp: 2025-06-21T16:54:30+00:00

from __future__ import annotations

from typing import Mapping

from pydantic import BaseModel, ConfigDict


class KeyValue(BaseModel):
    """
    A generic nested key-value map structure where outer keys map to objects, and inner keys map to string, number, or boolean values.
    """

    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    value: Mapping[str, Mapping[str, str | float | bool]]
