# generated by datamodel-codegen:
#   filename:  tmpeloxk4ty.json
#   timestamp: 2025-06-21T03:59:37+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class Label(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str,
        Field(
            description='A canonical definition for a short, human-readable UI label or title.',
            title='Label Field',
        ),
    ]
