# generated by datamodel-codegen:
#   filename:  tmpxaa54dj3.json
#   timestamp: 2025-06-21T03:59:38+00:00

from __future__ import annotations

from enum import Enum


class LinkStatus(str, Enum):
    """
    A canonical enum for the status of a cross-tenant link.
    """

    PendingApproval = 'PendingApproval'
    Approved = 'Approved'
    Revoked = 'Revoked'
    Declined = 'Declined'
