# generated by datamodel-codegen:
#   filename:  tmpw68z0klu.json
#   timestamp: 2025-06-21T16:54:31+00:00

from __future__ import annotations

from enum import Enum


class MomentType(str, Enum):
    """
    A canonical enum for the classification of a Moment entity's content.
    """

    Event = 'Event'
    Experience = 'Experience'
    Observation = 'Observation'
    Interaction = 'Interaction'
