# generated by datamodel-codegen:
#   filename:  tmpxj1oh246.json
#   timestamp: 2025-06-21T16:54:32+00:00

from __future__ import annotations

from enum import Enum


class MotifType(str, Enum):
    """
    A canonical enum of the types of recurring themes or motifs in memory.
    """

    Behavioral = 'Behavioral'
    Emotional = 'Emotional'
    Situational = 'Situational'
    Temporal = 'Temporal'
