# generated by datamodel-codegen:
#   filename:  tmpm72fjy74.json
#   timestamp: 2025-06-21T03:59:44+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class Name(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str,
        Field(
            description='The primary, human-readable name of an entity.',
            title='Name Field',
        ),
    ]
