# generated by datamodel-codegen:
#   filename:  tmph88u20bf.json
#   timestamp: 2025-06-21T16:54:33+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PhysicsConstants(BaseModel):
    """
    A structured definition for a set of physics constants.
    """

    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    decay_rate: float | None
    spring_constant: float | None
    max_tension: float | None
