# generated by datamodel-codegen:
#   filename:  tmpo0_8s9d4.json
#   timestamp: 2025-06-21T03:59:49+00:00

from __future__ import annotations

from enum import Enum


class Priority(str, Enum):
    """
    The user-assigned priority level.
    """

    Low = 'Low'
    Medium = 'Medium'
    High = 'High'
    Urgent = 'Urgent'
