# generated by datamodel-codegen:
#   filename:  tmp5al7_3vm.json
#   timestamp: 2025-06-21T03:59:50+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class QuantumCoherence(RootModel[float | None]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        float | None,
        Field(
            description='The quantum coherence level of the entity, representing its degree of superposition. Null for classical entities.',
            ge=0.0,
            le=1.0,
            title='QuantumCoherence',
        ),
    ]
