# generated by datamodel-codegen:
#   filename:  tmphd8rbkg7.json
#   timestamp: 2025-06-21T03:59:51+00:00

from __future__ import annotations

from enum import Enum


class ReconciliationTaskType(str, Enum):
    """
    A canonical enum for the types of reconciliation tasks performed by the Heddle engine.
    """

    Structural = 'Structural'
    Emotional = 'Emotional'
    Identity = 'Identity'
