# generated by datamodel-codegen:
#   filename:  tmpbmzb2w14.json
#   timestamp: 2025-06-21T16:54:34+00:00

from __future__ import annotations

from enum import Enum


class RelationshipType(str, Enum):
    """
    A canonical enum of all possible relationship types between Threads.
    """

    Family = 'Family'
    Friend = 'Friend'
    Romantic = 'Romantic'
    Professional = 'Professional'
    Acquaintance = 'Acquaintance'
    Adversarial = 'Adversarial'
