# generated by datamodel-codegen:
#   filename:  tmprk11mg2u.json
#   timestamp: 2025-06-21T16:54:34+00:00

from __future__ import annotations

from enum import Enum


class Role(str, Enum):
    """
    Defines the roles a user can have within a tenant.
    """

    Admin = 'Admin'
    Member = 'Member'
    Child = 'Child'
    Guardian = 'Guardian'
    ReadOnly = 'ReadOnly'
