# generated by datamodel-codegen:
#   filename:  tmpztu0gdwc.json
#   timestamp: 2025-06-21T03:59:57+00:00

from __future__ import annotations

from typing import Annotated, Sequence

from pydantic import ConfigDict, Field, RootModel


class SourceThreadAndBonds(RootModel[Sequence[str]]):
    """
    A list of Thread and Bond entity IDs that are the source for a derived cognitive entity like a Filament.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Sequence[str],
        Field(
            description='A list of Thread and Bond entity IDs that are the source for a derived cognitive entity like a Filament.',
            title='Source Threads and Bonds Field',
        ),
    ]
