# generated by datamodel-codegen:
#   filename:  tmpry0oh3fx.json
#   timestamp: 2025-06-21T03:59:59+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class StartDate(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str,
        Field(
            description='A canonical definition for an ISO 8601 timestamp with timezone.',
            title='Timestamp',
        ),
    ]
