# generated by datamodel-codegen:
#   filename:  tmp2a_euab9.json
#   timestamp: 2025-06-21T16:54:35+00:00

from __future__ import annotations

from enum import Enum


class Status(str, Enum):
    """
    The current status of a task or process.
    """

    Pending = 'Pending'
    InProgress = 'InProgress'
    Completed = 'Completed'
    Cancelled = 'Cancelled'
