# generated by datamodel-codegen:
#   filename:  tmpvmx29815.json
#   timestamp: 2025-06-21T16:54:36+00:00

from __future__ import annotations

from typing import Any, Mapping, Sequence

from pydantic import ConfigDict, RootModel


class StringValueMap(
    RootModel[
        Mapping[
            str, str | float | int | bool | Mapping[str, Any] | Sequence[Any] | None
        ]
        | None
    ]
):
    """
    A generic key-value map where keys are strings and values can be any JSON type. Used for flexible data structures like parameters or metadata.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: (
        Mapping[
            str, str | float | int | bool | Mapping[str, Any] | Sequence[Any] | None
        ]
        | None
    )
