# generated by datamodel-codegen:
#   filename:  tmpck3c1psc.json
#   timestamp: 2025-06-21T16:54:36+00:00

from __future__ import annotations

from enum import Enum


class SubscriptionPlan(str, Enum):
    """
    A canonical enum of all available subscription plans for a Tenant.
    """

    Free = 'Free'
    Personal = 'Personal'
    FamilyPlus = 'FamilyPlus'
    Enterprise = 'Enterprise'
