# generated by datamodel-codegen:
#   filename:  tmpaaca_g1l.json
#   timestamp: 2025-06-21T04:00:02+00:00

from __future__ import annotations

from enum import Enum


class SubscriptionPlan(str, Enum):
    """
    A canonical enum of all available subscription plans for a Tenant.
    """

    Free = 'Free'
    Personal = 'Personal'
    FamilyPlus = 'FamilyPlus'
    Enterprise = 'Enterprise'
