# generated by datamodel-codegen:
#   filename:  tmpunytrd5m.json
#   timestamp: 2025-06-21T04:00:08+00:00

from __future__ import annotations

from enum import Enum


class TemporalScope(str, Enum):
    """
    The temporal scope or duration of an entity or process.
    """

    Daily = 'Daily'
    Weekly = 'Weekly'
    Monthly = 'Monthly'
    Quarterly = 'Quarterly'
    Yearly = 'Yearly'
    Ongoing = 'Ongoing'
