# generated by datamodel-codegen:
#   filename:  tmpqru9t440.json
#   timestamp: 2025-06-21T04:00:10+00:00

from __future__ import annotations

from enum import Enum


class TenantPermission(str, Enum):
    """
    A canonical enum of permissions a user can have within a Tenant.
    """

    Read = 'Read'
    Write = 'Write'
    Contribute = 'Contribute'
    Administer = 'Administer'
