# generated by datamodel-codegen:
#   filename:  tmp0k4gxfda.json
#   timestamp: 2025-06-21T16:54:37+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class TenantId(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str,
        Field(
            description='A canonical definition for a Universally Unique Identifier (UUID).',
            title='UUID',
        ),
    ]
