# generated by datamodel-codegen:
#   filename:  tmphch9ez77.json
#   timestamp: 2025-06-21T16:54:38+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class Theme(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        str,
        Field(
            description='A concise statement of a focus, goal, or pattern.',
            title='Theme Field',
        ),
    ]
