# generated by datamodel-codegen:
#   filename:  tmpmfkpavth.json
#   timestamp: 2025-06-21T04:00:12+00:00

from __future__ import annotations

from enum import Enum


class ThreadStateReason(str, Enum):
    """
    A canonical enum of the machine-readable reasons for a Thread state change.
    """

    UserMarkedInactive = 'UserMarkedInactive'
    UserMarkedDeceased = 'UserMarkedDeceased'
    SystemDetectedInactivity = 'SystemDetectedInactivity'
    LifecycleCompleted = 'LifecycleCompleted'
