# generated by datamodel-codegen:
#   filename:  tmpz1ykanrz.json
#   timestamp: 2025-06-21T16:54:39+00:00

from __future__ import annotations

from enum import Enum


class ThreadStateResponse(str, Enum):
    """
    A canonical enum of the machine-readable reasons for a Thread state change.
    """

    UserMarkedInactive = 'UserMarkedInactive'
    UserMarkedDeceased = 'UserMarkedDeceased'
    SystemDetectedInactivity = 'SystemDetectedInactivity'
    LifecycleCompleted = 'LifecycleCompleted'
