# generated by datamodel-codegen:
#   filename:  tmpnllhqtdg.json
#   timestamp: 2025-06-21T04:00:11+00:00

from __future__ import annotations

from enum import Enum


class ThreadState(str, Enum):
    """
    A canonical enum of all possible lifecycle states for a Thread entity.
    """

    Active = 'Active'
    Inactive = 'Inactive'
    Fading = 'Fading'
    Archived = 'Archived'
