# generated by datamodel-codegen:
#   filename:  tmpr2d10kbp.json
#   timestamp: 2025-06-21T16:54:40+00:00

from __future__ import annotations

from enum import Enum


class ThreadType(str, Enum):
    """
    The Platonic Form of the Thread, enforcing abstract relationships.
    """

    Person = 'Person'
    Place = 'Place'
    Concept = 'Concept'
    GenericObject = 'GenericObject'
