# generated by datamodel-codegen:
#   filename:  tmpxgjtdoql.json
#   timestamp: 2025-06-21T04:00:20+00:00

from __future__ import annotations

from typing import Annotated, Sequence

from pydantic import ConfigDict, Field, RootModel


class Vec3(RootModel[Sequence[float]]):
    """
    A reusable data type for a vector of three f64 numbers, representing a physical property like position or velocity.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Sequence[float],
        Field(
            description='A reusable data type for a vector of three f64 numbers, representing a physical property like position or velocity.',
            max_length=3,
            min_length=3,
            title='3D Physics Vector',
        ),
    ]
