# generated by datamodel-codegen:
#   filename:  tmpqgb95pwk.json
#   timestamp: 2025-06-21T16:54:42+00:00

from __future__ import annotations

from typing import Annotated, Sequence

from pydantic import ConfigDict, Field, RootModel


class Vec6(RootModel[Sequence[float]]):
    """
    A reusable data type for a vector of six f64 numbers, used for momentum and forces in the 6 spatial dimensions of the manifold.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        Sequence[float],
        Field(
            description='A reusable data type for a vector of six f64 numbers, used for momentum and forces in the 6 spatial dimensions of the manifold.',
            max_length=6,
            min_length=6,
            title='6D Physics Vector',
        ),
    ]
