# generated by datamodel-codegen:
#   filename:  tmp9fe9nlkw.json
#   timestamp: 2025-06-21T04:00:24+00:00

from __future__ import annotations

from enum import Enum


class WeaveType(str, Enum):
    """
    Classifies the source format of a user's input 'Weave'.
    """

    text = 'text'
    audio = 'audio'
    image = 'image'
    document = 'document'
    system_event = 'system_event'
