# generated by datamodel-codegen:
#   filename:  tmpun0jhyft.json
#   timestamp: 2025-06-21T04:00:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Mapping

from pydantic import BaseModel, ConfigDict, Field


class Type(str, Enum):
    string = 'string'
    integer = 'integer'
    boolean = 'boolean'
    timestamp = 'timestamp'
    uuid = 'uuid'


class Columns(BaseModel):
    """
    Schema for defining a database table column.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    name: Annotated[
        str,
        Field(
            description='The primary, human-readable name of an entity.',
            title='Name Field',
        ),
    ]
    type: Type
    nullable: bool | None = False
    primary_key: bool | None = False
    unique: bool | None = False


class BondStateLog(BaseModel):
    """
    Defines the schema for the 'bond_state_log' database table, which stores an append-only history of a Bond's lifecycle state.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    tableName: Annotated[
        str, Field(description='The physical name of the table in the database.')
    ]
    columns: Annotated[
        Mapping[str, Columns],
        Field(
            description='A map of column names to their definitions.',
            title='BaseDatabaseColumns',
        ),
    ]
