name: Generate Backstage Catalog Info

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-catalog-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate root catalog-info.yaml
        uses: cds-snc/backstage-catalog-info-helper-action@main
        with:
          component-id: familiar-schema-system
          description: "Complete JSON schema system with assembly pipeline and code generation"
          component-type: system
          component-lifecycle: production
          component-owner: team:platform
          github-org: phaiel
          github-repo: familiar-schema
          path: ./

      - name: Generate schema assembly pipeline catalog-info.yaml
        uses: cds-snc/backstage-catalog-info-helper-action@main
        with:
          component-id: schema-assembly-pipeline
          description: "JSON schema assembly and code generation pipeline"
          component-type: library
          component-lifecycle: production
          component-owner: team:platform
          github-org: phaiel
          github-repo: familiar-schema
          path: ./docs/v3/

      - name: Generate base schemas catalog-info.yaml
        uses: cds-snc/backstage-catalog-info-helper-action@main
        with:
          component-id: base-schemas
          description: "Foundation JSON schemas that define core data structures"
          component-type: library
          component-lifecycle: production
          component-owner: team:platform
          github-org: phaiel
          github-repo: familiar-schema
          path: ./docs/v3/schemas/_base/

      - name: Generate component schemas catalog-info.yaml
        uses: cds-snc/backstage-catalog-info-helper-action@main
        with:
          component-id: component-schemas
          description: "ECS component schemas for physics simulation and memory management"
          component-type: library
          component-lifecycle: production
          component-owner: team:platform
          github-org: phaiel
          github-repo: familiar-schema
          path: ./docs/v3/schemas/components/

      - name: Generate entity schemas catalog-info.yaml
        uses: cds-snc/backstage-catalog-info-helper-action@main
        with:
          component-id: entity-schemas
          description: "Entity schemas defining cognitive threads and system entities"
          component-type: library
          component-lifecycle: production
          component-owner: team:platform
          github-org: phaiel
          github-repo: familiar-schema
          path: ./docs/v3/schemas/entities/

      - name: Generate generated code catalog-info.yaml
        uses: cds-snc/backstage-catalog-info-helper-action@main
        with:
          component-id: generated-code
          description: "Auto-generated Rust types from JSON schemas"
          component-type: library
          component-lifecycle: production
          component-owner: team:platform
          github-org: phaiel
          github-repo: familiar-schema
          path: ./src/generated/

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generate Backstage catalog-info.yaml files"
            git push 